-- TEMA DA AULA: COMO UTILIZAR MAIS DE UMA TABELA NUMA INSTRUÇÃO DE CONSULTA
-- 1) EQUAÇÃO DE JUNÇÃO
-- EXEMPLO:
SELECT CLIENTE.COD_CLI, CLIENTE.NOME_CLI, PEDIDO.NUM_PED
    FROM CLIENTE, PEDIDO
    WHERE CLIENTE.COD_CLI = PEDIDO.CD_CLI;
    
-- EXERCÍCIO 06
SELECT CLIENTE.COD_CLI, CLIENTE.NOME_CLI, PEDIDO.NUM_PED
    FROM CLIENTE, PEDIDO
    WHERE (CLIENTE.COD_CLI = PEDIDO.CD_CLI) AND (PEDIDO.PRAZO_ENTR > 15) AND ((UPPER(CLIENTE.UF) = 'SP') OR (UPPER(CLIENTE.UF) = 'RJ'));
