-- CRIAR TABELA (CREATE TABLE)
CREATE TABLE CLIENTE (
    COD_CLI INTEGER NOT NULL,
    NOME_CLI TEXT NOT NULL,
    ENDERECO TEXT,
    CIDADE TEXT,
    CEP TEXT,
    UF TEXT,
    PRIMARY KEY (COD_CLI)
);


-- DELETAR TABELA TODA (DROP TABLE)
DROP TABLE CLIENTE;


-- SELECIONAR COLUNAS DE UMA TABELA (SELECT... FROM...)
SELECT DESC_PROD, UNID_PROD, VAL_UNIT
    FROM PRODUTO;
    
SELECT * FROM CLIENTE;

SELECT * FROM PRODUTO;

SELECT NOME_CLI, CIDADE, UF
    FROM CLIENTE;


-- FILTRAR UMA SELEÇÃO (WHERE...)
SELECT NO_PED, CD_PROD, QTD_PED
    FROM ITEM_PEDIDO
    WHERE QTD_PED = 500;

SELECT * FROM ITEM_PEDIDO WHERE QTD_PED = 500;
