-- EXEMPLO ATUALIZAR REGISTROS
UPDATE PRODUTO
    SET VAL_UNIT = 8.00, UNID_PROD = 'KG'
    WHERE DESC_PROD = 'CIMENTO' OR DESC_PROD = 'FIO PLASTICO';
    
-- EXERCÍCIO 09: Atualizar o salário fixo de todos os vendedores em 27% mais uma bonificação de R$ 100,00
UPDATE VENDEDOR
    SET SAL_FIXO = ((SAL_FIXO * 1.27) + 100)
    
-- EXEMPLO DE EXCLUSÃO DE DADOS
DELETE FROM <TABELA>
    WHERE <CONDIÇÃO>;

-- DESAFIO:

-- 1) QUAIS SÃO OS CLIENTES LOCALIZADOS NA CIDADE DE NITERÓI?
SELECT COD_CLI, NOME_CLI, CIDADE
    FROM CLIENTE
    WHERE CIDADE = 'NITEROI';

-- 2) MOSTRAR TODOS OS PEDIDOS QUE NÃO TENHAM PRAZO DE ENTREGA SUPERIOR A 15 DIAS
SELECT NUM_PED, PRAZO_ENTR
    FROM PEDIDO
    WHERE PRAZO_ENTR <= 15;

-- 3) LISTAR TODOS OS VENDEDORES CUJOS OS NOMES NÃO COMECEM POR 'A'
SELECT COD_VEND, NOME_VEND
    FROM VENDEDOR
    WHERE NOME_VEND NOT LIKE 'A%';

-- 4)LISTAR OS NOMES, AS CIDADES E OS ESTADOS DE TODOS OS CLIENTES, ORDENADOS POR ESTADO E CIDADE DE FORMA DESCENDENTE
SELECT NOME_CLI, UF, CIDADE
    FROM CLIENTE
    ORDER BY UF DESC, CIDADE DESC;
    
-- 5) MOSTRAR A QUANTIDADE TOTAL PEDIDA PARA O PRODUTO CIMENTO, DE CÓDIGO 200
SELECT CD_PROD AS 'ID PRODUTO', SUM(QTD_PED) AS 'QUANTIDADE PEDIDA'
    FROM ITEM_PEDIDO
    WHERE CD_PROD = 200;

-- 6) A QUE CLIENTES ESTÃO ASSOCIADOS OS PEDIDOS EXISTENTES? LISTAR PELOS NOMES DOS CLIENTES:
SELECT C.NOME_CLI, P.NUM_PED
    FROM CLIENTE C, PEDIDO P
    WHERE C.COD_CLI = P.CD_CLI
    ORDER BY C.NOME_CLI;
    
-- 7) QUAIS SÃO SO CLIENTES QUE TÊM PEDIDOS COM PRAZOS DE ENTREGA SUPERIORES A 15 DIAS E QUE ESTÃO LOCALIZADOS NOS ESTADOS DE SÃO PAULO OU DO RIO DE JANEIRO?
SELECT C.NOME_CLI
    FROM CLIENTE C, PEDIDO P
    WHERE (C.COD_CLI = P.CD_CLI) AND (P.PRAZO_ENTR > 15) AND (C.UF IN('SP', 'RJ'))
    ORDER BY C.NOME_CLI;

-- 8) MOSTRAR OS PEDIDOS DOS CLIENTES E SEUS RESPECTIVOS PRAZOS DE ENTREGA ORDENADOS DO MAIOR PARA O MENOR
SELECT  C.NOME_CLI, P.NUM_PED, P.PRAZO_ENTR
    FROM CLIENTE C, PEDIDO P
    WHERE (C.COD_CLI = P.CD_CLI)
    ORDER BY P.PRAZO_ENTR DESC;
    
-- 9) MOSTRE OS NOMES DE TODOS OS VENDEDORES QUE VENDERAM "CHAPA DE AÇO" EM QUANTIDADE SUPERIOR A 300KG.
SELECT DISTINCT V.NOME_VEND
    FROM VENDEDOR V, ITEM_PEDIDO I, PRODUTO P
    WHERE (
             SELECT SUM(I.QTD_PED) AS QTD_VENDIDA
                 FROM ITEM_PEDIDO I, PRODUTO P
                 WHERE (P.DESC_PROD LIKE '%CHAPA DE ACO%')
         );

-- 10) QUANTOS CLIENTES FIZERAM PEDIDOS COM A VENDEDORA ANA CRISTINA
SELECT  V.NOME_VEND AS 'VENDEDOR(A)', COUNT(0) AS 'QUANTIDADE DE CLIENTES'
    FROM VENDEDOR V, PEDIDO P
    WHERE (P.CD_VEND = V.COD_VEND) AND V.NOME_VEND = 'ANA CRISTINA';

-- 11) QUANTOS CLIENTES DAS CIDADES DO RIO DE JANEIRO E NITERÓI TIVERAM SEUS PEDIDOS TIRADOS COM A VENDEDORA ANA CRISTINA?


-- 12) QUAIS VENDEDORES QUE SÓ VENDERAM PRODUTOS COMERCIALIZADOS EM QUILOGRAMAS (KG)?
