-- TEMA DA AULA: COMO UTILIZAR MAIS DE UMA TABELA NUMA INSTRUÇÃO DE CONSULTA
-- 1) EQUAÇÃO DE JUNÇÃO
-- EXEMPLO:
SELECT CLIENTE.COD_CLI, CLIENTE.NOME_CLI, PEDIDO.NUM_PED
    FROM CLIENTE, PEDIDO
    WHERE CLIENTE.COD_CLI = PEDIDO.CD_CLI;
    
-- EXERCÍCIO 06
SELECT CLIENTE.COD_CLI, CLIENTE.NOME_CLI, PEDIDO.NUM_PED
    FROM CLIENTE, PEDIDO
    WHERE (CLIENTE.COD_CLI = PEDIDO.CD_CLI) 
        AND (PEDIDO.PRAZO_ENTR > 15) 
        AND ((UPPER(CLIENTE.UF) = 'SP') OR (UPPER(CLIENTE.UF) = 'RJ'));
        -- AND (UPPER(CLIENTE.UF) IN ('SP','RJ')
        
-- EXEMPLO USANDO ALIAS: Nome de vendedores que ganham mais de 1000 reais com prazo de entrega superior a 15 e ordenado de forma ASC pelo nome.
SELECT DISTINCT V.NOME_VEND, P.PRAZO_ENTR
    FROM VENDEDOR V, PEDIDO P
    WHERE V.COD_VEND = P.CD_VEND
        AND V.SAL_FIXO > 1000
        AND P.PRAZO_ENTR > 15
    ORDER BY V.NOME_VEND;
